---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:

  - name: install ntp, mssql
    apt:
      name:
        - ntp
        - mysql-server
      state: latest
      update_cache: yes
